import {Department} from './Department';
import {Address} from './Address';
import {Post} from './Post';
import {UserConfigs} from './UserConfigs';
import {NotificationMessage} from './NotificationMessage';
import {Attendance} from './Attendance';
import {Absence} from './Absence';
import {Role} from "./Role";
export class User {
  userId: number;
  cin: string;
  name: string;
  firstName: string;
  gender: string;
  birthDate: string;
  hireDay: Date;
  phone: string;
  email: string;
  password: string;
  department: Department;
  addresses: Address[];
  post: Post;
  userConfigs: UserConfigs[];
  image: string;
  fullImage: any;
  notificationMessages: NotificationMessage[];
  attendances: Attendance[];
  absences: Absence[];
  checkInStatus: string;
  checkInMsg: string;
  checkOutStatus: string;
  checkOutMsg: string;
  roles: Role[];
  }
